# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for MCP Docent Server
# Use official Node.js LTS on Alpine for minimal footprint
FROM node:lts-alpine AS builder

WORKDIR /app

# Install dependencies without running any prepare scripts
COPY package.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source code
COPY src ./src

# Build TypeScript
RUN npm run build

# Prepare production image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy package.json and installed modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules

# Copy built artifacts
COPY --from=builder /app/dist ./dist

# Define command
CMD ["node", "dist/index.js"]
